name: php80

on: [push, pull_request]

env:
  DEFAULT_COMPOSER_FLAGS: "--ignore-platform-reqs --no-interaction --no-progress --optimize-autoloader"

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: curl, mbstring, dom, intl
          ini-values: date.timezone='UTC'
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Install dependencies
        run: composer install $DEFAULT_COMPOSER_FLAGS
      - name: PHP Unit tests
        run: vendor/bin/phpunit --verbose --coverage-clover=coverage.clover
      - name: Code coverage
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
